---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: heading
  label: Blogs
- type: heading
  label: Documentation
- type: document
  path: data/docs-menu.json
  label: Docs menu
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - AIRTABLE_API_KEY=keyZK6U6U4RUBHENh
  - AIRTABLE_AUTHOR_TABLE=author
  - AIRTABLE_BASE_ID=appP3wGL6qGpzB3mj
  - AIRTABLE_BLOG_TABLE=blog
  - AIRTABLE_PAIR_PROGRAMMING=pair programming
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
