---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: heading
  label: Blog
- type: document
  path: data/author.json
  label: Author
- type: directory
  path: blogs
  label: Blogs
  create: all
  match: "**/*"
- type: heading
  label: Documentation
- type: document
  path: data/docs-menu.json
  label: Docs menu
- type: directory
  path: docs
  label: Documentation
  create: all
  match: "**/*"
- type: heading
  label: Release notes
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
