name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Node version
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install packages
        run: npm install

      - name: Run build
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: "site"
          path: "dist"
