name: Trigger netlify build

jobs:
  build:
    name: Build request netlify
    runs-on: ubuntu-latest

    steps:
      - name: Curl request
        run: curl -X POST -d '{}' ${{ secrets.NETLIFY_BUILD_HOOK }}
